export const DataBase = [
    {
        id: "15215vd",
        nombre: "Eduardo",
        estado: "Bloqueado",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "1500$",
        facturacionEvento: "200$",
        facturacionSAAS: "100$",
        SaasEventos: "100$",
        referido: "Discoteca ternera",
        producto: "Lista de invitaciones",
        fuente: "Fin de año",
        estadoRecompensa: "Bloqueado",
        documento:"24058059",
        descripcion: "Evento de night club",
        deuda:"+500$",
        haber:"0",
    },
    {
        id: "15215as",
        nombre: "Andres",
        estado: "Inactivo",
        fecha: "Julio 10, 2023 3:00pm",
        amount: "500$",
        facturacionEvento: "100$",
        facturacionSAAS: "400$",
        SaasEventos: "200$",
        referido: "Jose Andres",
        producto: "Saas app bodas",
        fuente: "Sin información",
        estadoRecompensa: "Sin servicios",
        documento:"18056057",
        descripcion: "Suscripciones generales",
        deuda:"+300$",
        haber:"0",
    },
    {
        id: "15215vv",
        nombre: "Pedro",
        estado: "En espera",
        fecha: "Agosto 1, 2023 1:00pm",
        amount: "1000$",
        facturacionEvento: "500$",
        facturacionSAAS: "100$",
        SaasEventos: "100$",
        referido: "Muerde la carne",
        producto: "App-Empresas",
        fuente: "Suscripción premium",
        estadoRecompensa: "Disponible",
        documento:"16872563",
        descripcion: "Suscripciones premiun",
        deuda:"+200$",
        haber:"0",
        
    },
    {
        id: "15215da",
        nombre: "Isabel",
        estado: "Bloqueado",
        fecha: "Julio 30, 2023 5:00pm",
        amount: "150$",
        facturacionEvento: "500$",
        facturacionSAAS: "400$",
        SaasEventos: "100$",
        referido: "Maruma center",
        producto: "Venta de entradas",
        fuente: "Concierto",
        estadoRecompensa: "Disponible",
        documento:"16872563",
        descripcion: "Suscripciones premiun",
        deuda:"+200$",
        haber:"0",
    },
    {
        id: "15215as",
        nombre: "Lucas",
        estado: "En espera",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "2000$",
        facturacionEvento: "100$",
        facturacionSAAS: "100$",
        SaasEventos: "50$",
        referido: "Hotel Inter",
        producto: "App-Empresas",
        fuente: "Suscripción premium",
        estadoRecompensa: "En espera",
        documento:"20851951",
        descripcion: "liquidación empleados",
        deuda:"0",
        haber:"-100$",
    },
    {
        id: "15215wg",
        nombre: "Jennifer",
        estado: "Activo",
        fecha: "Diciembre 15, 2023 5:00pm",
        amount: "500$",
        facturacionEvento: "500$",
        facturacionSAAS: "1000$",
        SaasEventos: "500$",
        referido: "Albahacarestaurante",
        producto: "App-Evento",
        fuente: "Suscripción premium",
        estadoRecompensa: "Disponible",
        documento:"28654852",
        descripcion: "proveedores",
        deuda:"0",
        haber:"-150$",
    },
    {
        id: "15215fds",
        nombre: "Norberto",
        estado: "Activo",
        fecha: "Enero 15, 2023 5:00pm",
        amount: "50$",
        facturacionEvento: "500$",
        facturacionSAAS: "10$",
        SaasEventos: "400$",
        referido: "Snou",
        producto: "Directorio Bodas",
        fuente: "Publicidad",
        estadoRecompensa: "En espera",
        documento:"24058059",
        descripcion: "Evento de night club",
        deuda:"+500$",
        haber:"0",
    },
    {
        id: "15215sdas",
        nombre: "Mariela",
        estado: "Activo",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "1100$",
        facturacionEvento: "800$",
        facturacionSAAS: "200$",
        SaasEventos: "100$",
        referido: "Hotel Cari",
        producto: "App-Evento",
        fuente: "Suscripción premium",
        estadoRecompensa: "Disponible",
        documento:"16872563",
        descripcion: "Suscripciones premiun",
        deuda:"+200$",
        haber:"0",
    },
    {
        id: "15215dgv",
        nombre: "Alonso",
        estado: "En espera",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "400$",
        facturacionEvento: "500$",
        facturacionSAAS: "100$",
        SaasEventos: "200$",
        referido: "Finca aurora",
        producto: "App-Evento",
        fuente: "Suscripción premium",
        estadoRecompensa: "En espera",
        documento:"18056057",
        descripcion: "Suscripciones generales",
        deuda:"+300$",
        haber:"0",
    },
    {
        id: "15215ge",
        nombre: "Fabiana",
        estado: "Activo",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "3000$",
        facturacionEvento: "1000$",
        facturacionSAAS: "500$",
        SaasEventos: "500$",
        referido: "Finca Santa teresa",
        producto: "App-Evento",
        fuente: "Suscripción premium",
        estadoRecompensa: "Disponible",
        documento:"28654852",
        descripcion: "proveedores",
        deuda:"0",
        haber:"-150$",
    },
    {
        id: "15215vfse",
        nombre: "Jesus",
        estado: "Activo",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "20$",
        facturacionEvento: "200$",
        facturacionSAAS: "100$",
        SaasEventos: "100$",
        referido:"Santa restaurant",
        producto:"App-Bodas",
        fuente:"Suscripción basico",
        estadoRecompensa:"Disponible",
        documento:"20851951",
        descripcion: "liquidación empleados",
        deuda:"0",
        haber:"-100$",
    },
    {
        id: "15215sasdfc",
        nombre: "Edward",
        estado: "Activo",
        fecha: "Julio 25, 2023 5:00pm",
        amount: "0$",
        facturacionEvento: "800$",
        facturacionSAAS: "100$",
        SaasEventos: "400$",
        referido:"Pasapalos Maria",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"16872563",
        descripcion: "Suscripciones premiun",
        deuda:"+200$",
        haber:"0",
    },
    {
        id: "15215acg",
        nombre: "Carlos",
        estado: "Bloqueado",
        fecha: "Junio 15, 2023 5:00pm",
        amount: "20$",
        facturacionEvento: "900$",
        facturacionSAAS: "800$",
        SaasEventos: "100$",
        referido:"DJ alberto",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"20851951",
        descripcion: "liquidación empleados",
        deuda:"0",
        haber:"-100$",
        
    },
    {
        id: "15215gcvs",
        nombre: "Fernandez",
        estado: "Activo",
        fecha: "Febrero 15, 2023 5:00pm",
        amount: "40$",
        facturacionEvento: "400$",
        facturacionSAAS: "400$",
        SaasEventos: "100$",
        referido:"Transportes andres",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"24058059",
        descripcion: "Evento de night club",
        deuda:"+500$",
        haber:"0",
    },
    {
        id: "15215cdga",
        nombre: "Juan",
        estado: "En espera",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "80$",
        facturacionEvento: "10$",
        facturacionSAAS: "10$",
        SaasEventos: "1$",
        referido:"Decoraciones Julia",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"16872563",
        descripcion: "Suscripciones premiun",
        deuda:"+200$",
        haber:"0",
    },
    {
        id: "15215asdaac",
        nombre: "Eduardo",
        estado: "Activo",
        fecha: "Noviembre 15, 2023 5:00pm",
        amount: "400$",
        facturacionEvento: "500$",
        facturacionSAAS: "100$",
        SaasEventos: "100$",
        referido:"Decoraciones maria",
        producto:"app-Eventos",
        fuente:"Publicidad",
        estadoRecompensa:"En espera",
        documento:"28654852",
        descripcion: "proveedores",
        deuda:"0",
        haber:"-150$",
    },
    {
        id: "15215dasdaxa",
        nombre: "Luis",
        estado: "Activo",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "800$",
        facturacionEvento: "400$",
        facturacionSAAS: "1200$",
        SaasEventos: "600$",
        referido:"Maria Daniela",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"20851951",
        descripcion: "liquidación empleados",
        deuda:"0",
        haber:"-100$",
    },
    {
        id: "15215vdscxx",
        nombre: "Arturo",
        estado: "En espera",
        fecha: "Noviembre 15, 2023 5:00pm",
        amount: "10$",
        facturacionEvento: "100$",
        facturacionSAAS: "100$",
        SaasEventos: "100$",
        referido:"Luces Jose",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"18056057",
        descripcion: "Suscripciones generales",
        deuda:"+300$",
        haber:"0",
    },
    {
        id: "15215dseca",
        nombre: "Jafet",
        estado: "Inactivo",
        fecha: "Febrero 15, 2023 5:00pm",
        amount: "50$",
        facturacionEvento: "500$",
        facturacionSAAS: "300$",
        SaasEventos: "200$",
        referido:"Transportes Jose",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"20851951",
        descripcion: "liquidación empleados",
        deuda:"0",
        haber:"-100$",
    },
    {
        id: "15215cdaa",
        nombre: "Ronald",
        estado: "Inactivo",
        fecha: "Octubre 15, 2023 5:00pm",
        amount: "700$",
        facturacionEvento: "900$",
        facturacionSAAS: "200$",
        SaasEventos: "110$",
        referido:"Floristeria Yuliana",
        producto:"App-Bodas",
        fuente:"Suscripcion premium",
        estadoRecompensa:"Disponible",
        documento:"24058059",
        descripcion: "Evento de night club",
        deuda:"+500$",
        haber:"0",
    },
    {
        id: "15215aaascxc",
        nombre: "Montero",
        estado: "Activo",
        fecha: "Noviembre 10, 2023 5:00pm",
        amount: "5$",
        facturacionEvento: "2000$",
        facturacionSAAS: "400$",
        SaasEventos: "150$",
        referido:"Decoraciones daniela",
        producto:"Directorio bodas",
        fuente:"Publicidad",
        estadoRecompensa:"Disponible",
        documento:"28654852",
        descripcion: "proveedores",
        deuda:"0",
        haber:"-150$"
    },
    {
        id: "15215ggg",
        nombre: "Jose",
        estado: "Activo",
        fecha: "Julio 15, 2023 5:00pm",
        amount: "40$",
        facturacionEvento: "20000$",
        facturacionSAAS: "500$",
        SaasEventos: "500$",
        referido:"Mesas Jose",
        producto:"App-Eventos",
        fuente:"Plan Premium",
        estadoRecompensa:"Bloqueado",
        documento:"24058059",
        descripcion: "Evento de night club",
        deuda:"+500$",
        haber:"0",
    },

]